name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Set version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Restore dependencies
      run: dotnet restore source/NuLink.sln
    
    - name: Build
      run: dotnet build source/NuLink.sln --configuration Release --no-restore /p:Version=${{ steps.get_version.outputs.VERSION }}
    
    - name: Pack
      run: dotnet pack source/NuLink.Cli/NuLink.Cli.csproj --configuration Release --no-build --output ./nupkgs /p:Version=${{ steps.get_version.outputs.VERSION }}
    
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate